apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-operator

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: crd-operator
  namespace: default


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: operator
  name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: operator
  template:
    metadata:
      labels:
        run: operator
    spec:
      serviceAccount: crd-operator
      containers:
      - image: crd-operator:v1
        imagePullPolicy: Never
        name: operator
