apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth
        image: authserver:v1
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: api-ca
          mountPath: /app/ssl/ca.crt
          subPath: ca.crt
        - name: ssl
          mountPath: /app/ssl
      volumes:
      - name: api-ca
        hostPath:
          path: /etc/kubernetes/pki/ca.crta
        readOnly: true
      - name: ssl
        secret:
          secretName: auth-server-tls
      nodeSelector:
        app: auth-server
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-server
  name: auth
  namespace: kube-system
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 31443
  selector:
    app: auth-server
  type: NodePort
