version: '3.1'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:6000
    links:
      - "registry:registry"


